declare interface IAlbum {
  idAlbum?: string;
  idArtist?: string;
  idLabel?: string;
  strAlbum?: string;
  strAlbumStripped?: string;
  strArtist?: string;
  strArtistStripped?: string;
  intYearReleased?: string;
  strStyle?: string;
  strGenre?: string;
  strLabel?: string;
  strReleaseFormat?: string;
  intSales?: string;
  strAlbumThumb?: string;
  strAlbumThumbHQ?: string | null;
  strAlbumThumbBack?: string;
  strAlbumCDart?: string;
  strAlbumSpine?: string;
  strAlbum3DCase?: string;
  strAlbum3DFlat?: string;
  strAlbum3DFace?: string;
  strAlbum3DThumb?: string;
  strDescriptionEN?: string | null;
  strDescriptionDE?: string | null;
  strDescriptionFR?: string | null;
  strDescriptionCN?: string | null;
  strDescriptionIT?: string | null;
  strDescriptionJP?: string | null;
  strDescriptionRU?: string | null;
  strDescriptionES?: string | null;
  strDescriptionPT?: string | null;
  strDescriptionSE?: string | null;
  strDescriptionNL?: string | null;
  strDescriptionHU?: string | null;
  strDescriptionNO?: string | null;
  strDescriptionIL?: string | null;
  strDescriptionPL?: string | null;
  intLoved?: string;
  intScore?: string;
  intScoreVotes?: string;
  strReview?: string;
  strMood?: string;
  strTheme?: string | null;
  strSpeed?: string;
  strLocation?: string | null;
  strMusicBrainzID?: string;
  strMusicBrainzArtistID?: string;
  strAllMusicID?: string;
  strBBCReviewID?: string;
  strRateYourMusicID?: string;
  strDiscogsID?: string;
  strWikidataID?: string;
  strWikipediaID?: string;
  strGeniusID?: string | null;
  strLyricWikiID?: string | null;
  strMusicMozID?: string;
  strItunesID?: string | null;
  strAmazonID?: string | null;
  strLocked?: string;
}
